# Generated by Django 4.2.2 on 2023-06-15 16:37

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Characters",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("picture", models.URLField()),
                ("char_id", models.IntegerField()),
                ("description", models.CharField(max_length=500)),
            ],
        ),
    ]
